// <auto-generated />
using System;
using CloudKB.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CloudKB.Infrastructure.Migrations
{
    [DbContext(typeof(CloudKbDbContext))]
    [Migration("20260529142834_AddTenantUsers")]
    partial class AddTenantUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CloudKB.Infrastructure.IndexAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommitMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SectionsAffected")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LoggedAt")
                        .HasDatabaseName("ix_index_audit_logs_tenant_logged");

                    b.ToTable("index_audit_logs", (string)null);
                });

            modelBuilder.Entity("CloudKB.Infrastructure.IndexCompilationJob", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CompileDurationMs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("FileNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("FilesProcessed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("S3StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SectionsCompiled")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskId");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("ix_compilation_jobs_requested_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_compilation_jobs_tenant_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_compilation_jobs_status");

                    b.ToTable("index_compilation_jobs", (string)null);
                });

            modelBuilder.Entity("CloudKB.Infrastructure.TenantFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastIndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_files_tenant_id");

                    b.HasIndex("TenantId", "FileName")
                        .IsUnique()
                        .HasDatabaseName("uq_tenant_files_tenant_filename");

                    b.ToTable("tenant_files", (string)null);
                });

            modelBuilder.Entity("CloudKB.Infrastructure.TenantFileState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastIndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_file_states_tenant_id");

                    b.ToTable("tenant_file_states", (string)null);
                });

            modelBuilder.Entity("CloudKB.Infrastructure.TenantSection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("HeadingPath")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string>("Tokens")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_sections_tenant_id");

                    b.HasIndex("TenantId", "FileName")
                        .HasDatabaseName("ix_tenant_sections_tenant_file");

                    b.ToTable("tenant_sections", (string)null);
                });

            modelBuilder.Entity("CloudKB.Infrastructure.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_tenant_users_username");

                    b.ToTable("tenant_users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
